In [1]:
import torch

In [2]:
w = torch.tensor(2.0, requires_grad = True)
b = torch.tensor(-1.0, requires_grad = True)

In [3]:
def forward(x):
    yhat = w * x + b
    return yhat

In [4]:
x = torch.tensor([[1.0]])
yhat = forward(x)
print("The prediction: ", yhat)

The prediction:  tensor([[1.]], grad_fn=<AddBackward0>)


In [5]:
x = torch.tensor([[1.0], [2.0]])
print("The shape of x: ", x.shape)
yhat = forward(x)
print("The prediction: ", yhat)

The shape of x:  torch.Size([2, 1])
The prediction:  tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


In [10]:
from torch.nn import Linear

torch.manual_seed(1)

lr = Linear(in_features=1, out_features=1, bias=True)
print("Parameters w and b: ", list(lr.parameters()))

print("Python dictionary: ",lr.state_dict())
print("keys: ",lr.state_dict().keys())
print("values: ",lr.state_dict().values())

Parameters w and b:  [Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]
Python dictionary:  OrderedDict([('weight', tensor([[0.5153]])), ('bias', tensor([-0.4414]))])
keys:  odict_keys(['weight', 'bias'])
values:  odict_values([tensor([[0.5153]]), tensor([-0.4414])])


In [12]:
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward0>)


In [14]:
from torch import nn

class LR(nn.Module):

    def __init__(self, input_size, output_size):

        super(LR, self).__init__()
        self.linear = nn.Linear(input_size, output_size)

    def forward(self, x):
        out = self.linear(x)
        return out

lr = LR(1, 1)
print("The parameters: ", list(lr.parameters()))
print("Linear model: ", lr.linear)

The parameters:  [Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]
Linear model:  Linear(in_features=1, out_features=1, bias=True)


In [15]:
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.2755],
        [0.0816]], grad_fn=<AddmmBackward0>)


In [18]:
import numpy as np
import torch

X = torch.arange(-3, 3, 0.1).view(-1, 1)
f = 1 * X - 1
Y = f + 0.1 * torch.randn(X.size())

In [19]:
def forward(x):
    return w * x + b

def criterion(yhat,y):
    return torch.mean((yhat-y)**2)

w = torch.tensor(-15.0, requires_grad = True)
b = torch.tensor(-10.0, requires_grad = True)

lr = 0.1
LOSS = []

In [20]:
def train_model(iter):

    for epoch in range(iter):

        Yhat = forward(X)

        loss = criterion(Yhat, Y)

        LOSS.append(loss)

        loss.backward()

        w.data = w.data - lr * w.grad.data
        b.data = b.data - lr * b.grad.data

        w.grad.data.zero_()
        b.grad.data.zero_()

In [21]:
train_model(15)

In [29]:
print(w.data)
print(b.data)

tensor(0.9908)
tensor(-1.3391)
